stages:
  - build
  - deploy

build:windows:
  stage: build
  tags: windows
  only: master
  variables:
    CI_PROJECT_PATH: deepmanyy/easydeepnude
  before_script:
    - cd $CI_PROJECT_DIR/src/gui
    - yarn install --force --no-lockfile
  script:
    - cd $CI_PROJECT_DIR/src/cli
    - pyinstaller main.py -y --onedir --name "cli" --distpath "../../dist"
    - cd $CI_PROJECT_DIR/src/gui
    - yarn build
  artifacts:
    name: "PepeNude-windows-x86_64-v$CI_COMMIT_TAG"
    paths:
      - $CI_PROJECT_DIR/dist/gui/
      - $CI_PROJECT_DIR/dist/cli/

build:linux:
  stage: build
  tags: linux
  only: master
  variables:
    CI_PROJECT_PATH: deepmanyy/easydeepnude
  before_script:
    - cd $CI_PROJECT_DIR/src/gui
    - yarn install --force --no-lockfile
  script:
    - cd $CI_PROJECT_DIR/src/cli
    - pyinstaller main.py -y --onedir --name "cli" --distpath "../../dist"
    - cd $CI_PROJECT_DIR/src/gui
    - yarn build
  artifacts:
    name: "PepeNude-linux-x86_64-v$CI_COMMIT_TAG"
    paths:
      - $CI_PROJECT_DIR/dist/gui/
      - $CI_PROJECT_DIR/dist/cli/
